### ISSUE TITLE
TypeError: 'bool' object is not iterable

### ISSUE THREAD

**Issue by enviz** [aalireza/SimpleAudioIndexer#11]
Hey. I really like the technology you're implementing here. It's amazing.

I am a simple man using this on windows. I read the documentation and tried this on a docker shell/bash window. I've read the instructions but I am getting the following error. 
Please help me solve this.

![Screenshot (15)](https://user-images.githubusercontent.com/48526315/54489632-5b16d380-48d4-11e9-9bde-4a3fc36f0aee.png)

**Comment by aalireza** [comment]
Please include the command itself in your screenshot. Also add a `--verbose` to the end of the command. paste here everything you're receiving.

**Comment by enviz** [comment]
Ok I added --verbose at the end as well.

This time it's a new error: Path doesn't exist
I don't know why this python script won't recognizing the path when the path actually exists.

![Screenshot (17)](https://user-images.githubusercontent.com/48526315/54509042-1a6b9880-496e-11e9-821e-290ad4bac47e.png)

**Comment by enviz** [comment]
here are a few others that I tried. In this one,I added an extra backslash in the path.
Here,the error says that the arguments are missing. I do not understand why. Please let me know,thanks in advance

![Screenshot (19)](https://user-images.githubusercontent.com/48526315/54509258-fceafe80-496e-11e9-8719-2e97ed26d698.png)

**Comment by aalireza** [comment]
@enviz 

1. The path isn't found, because you're giving a path on your windows system, from an Ubuntu container. Copy your material into docker and try again.

2. The reason you're getting a new error is most likely because `\` is an escape character and then argparse freaks out.

3. `This time it's a new error` after adding `--verbose` is misleading to say the least. You had ran the code previously from `runpy` from most likely bash on windows. The reason you're getting a new error this time, is because last time you didn't follow the documentation properly.

**Comment by enviz** [comment]
Hey,thanks for replying. I think you're right.
But here's the thing. I have never used Ubuntu so I don't know how to set the path in the Ubuntu container,(In this case,it's the docker). 
This might sound like a noob question could you please tell me how to modify this path in such a way that the path will be recognized? (I know that you don't use Windows ,but please help me out )
my working directory or home  is  C:\Users\Vikram

My wav file is in the folder simple:  C:\Users\Vikram\simple

Please let me know because I am not familiar with how the path is provided in Linux system,thanks
