### ISSUE TITLE
Error: The resulting request from Watson was unintelligible

### ISSUE THREAD

**Issue by kevinashaw** [aalireza/SimpleAudioIndexer#3]
Hello.
Thank you for making this project.  
I'm trying to index a short .wav file with the following python (2.7):
```
from SimpleAudioIndexer import SimpleAudioIndexer as sai
indexer = sai("...","...",src_dir="//Users/.../temp")
indexer.index_audio()                     
print(indexer.get_timestamped_audio())    
```
I'm getting the following error message:
`{u'code_description': u'Bad Request', u'code': 400, u'error': u'No speech detected for 30s.'}
The resulting request from Watson was unintelligible.`
I've attached the sound file (though I had to add a .zip to the filename to get it to transfer; its *not* actually a .zip file).
Can you recommend a good way to debug this.  Is there a verbose option from the Watson routines?
Thanks!
-K

[sensorlog_2017-02-08_01-10-45-332_Dev26c5_Loc27_TypeAUDIO.wav.zip](https://github.com/aalireza/SimpleAudioIndexer/files/760184/sensorlog_2017-02-08_01-10-45-332_Dev26c5_Loc27_TypeAUDIO.wav.zip)

**Comment by aalireza** [comment]
Hi,

Thanks for using it! 

I see. My output is this:
```
{'sensorlog_2017-02-08_01-10-45-332_Dev26c5_Loc27_TypeAUDIO.wav': [[u'hello', 2.03, 2.61], [u'hello', 2.96, 3.59], [u'hello', 3.95, 4.48], [u'hello', 6.21, 6.74]]}
```
There shouldn't be any problem on the Watson side. The problem necessarily must be before uploading the audio. My guess is the pre-existing audio in `//Users/.../temp/filtered` or `//Users/.../temp/staging/` directories are causing the problem, since it said for 30 seconds (threshold) no speech was detected.


Could you please do the following and let me know about the results:

1. Proceed exactly like you did, but in a verbose mode `indexer = sai(..., verbose=True)` upon initialization or `indexer.verbose = True` before calling `indexer.index_audio` and see which file is being uploaded.

2. Call 
```
>>> indexer.index_audio(name="sensorlog_2017-02-08_01-10-45-332_Dev26c5_Loc27_TypeAUDIO")
>>> print(indexer.get_timestamped_audio())
```
If the return is successful, then those intermediary files are problematic.

3. Remove `filtered` and `staging` sub directories and call the script from the command line like below:
```
sai -u USERNAME -p PASSWORD -d "//Users/.../temp" -t -search "hello"
```
The script initializes indexer in a `with` statement, so it cleans up after itself.



---

Verbosity is defined for entire object that was initialized, not a single method. If `self.verbose == True`, then `index_audio` method prints the name of the audio file from staging sub directory is being uploaded, any more than that is out of control and is on the Watson side. I'll add a verbose setter/getter though for clarity.

**Comment by kevinashaw** [comment]
Thank you for the help.  Cleaning out the directory did help.  It looks like there was a file stuck there.
Here is the result now with that file:
`{'sensorlog_2017-02-08_01-10-45-332_Dev26c5_Loc27_TypeAUDIO.wav': [[u'hello', 2.03, 2.61], [u'hello', 2.96, 3.59], [u'hello', 3.95, 4.48], [u'hello', 6.21, 6.74]]}`
However, I have another file, with clear speech in it, that is still returning:
`{u'code_description': u'Bad Request', u'code': 400, u'error': u'No speech detected for 30s.'}
The resulting request from Watson was unintelligible.`
Is there a way to get better diagnostics from Watson? (Though I have a feeling that it is the nature of DNNs not to be able to provide diagnostic information)
Thanks.
-K

**Comment by kevinashaw** [comment]
I can send you a subsection of the troublesome audio file privately, if you want to see/hear it.  Thanks.  -K

**Comment by kevinashaw** [comment]
I have tested it some more and discovered that if I use only the first 250 seconds of the file it processes fine with Watson and returns reasonable results.  But that if I use the 300 seconds (9.6MB), that is 30 seconds longer, then it returns the "unintelligible" result.  I'm using pydub to handle the audio file processing, since the original files are M4A/AAC files, and I'm converting them to .wav prior to using SAI.  Its odd that the first 250 seconds would work fine.  I've listened to the audio of the additional 30 seconds and hear no issues with it.  I think I should just submit this to IBM support.

**Comment by aalireza** [comment]
@kevinashaw 

1. I'd very much appreciate it if you could send me the audio file. 

2. Watson's default threshold is 30 seconds, which means it returns an error if for 30 seconds it doesn't hear anything. I think the problem would be resolved if I calculate the length of the audio file and increase the threshold to that length, prior to feeding it to Watson. However I need that audio file to work with, since Watson apparently handles everything I have.

3. Try lowering down the `word_alternative_threshold` (default at 0.9 which means only top 10% is returned), or possibly change `model` which is currently `en-US_BroadbandModel`. But I can give a definitive answer if I have the audio file.

3. The file handling for the current version of SAI is very buggy for context free situations (i.e. where initialization is not within a `with` statement). The new version fixes it, it also adds CMU Sphinx support which uses ffmpeg to regularize encoding. I think I'll add a regularizer for Watson as well.

**Comment by kevinashaw** [comment]
@aalireza 
Thank you for the help.
I worked out the issue through IBM BlueMix support.  I sent them several working and non-working files and they concluded that there were in fact large gaps in speech in the files (the files narrate research activities which do have large gaps).  I think the "unintelligible" error is what threw me.
They recommended modifying the inactivity_timeout settings, also, that setting the value to -1 would set an infinite inactivity_timeout.  
I modified my local branch of SAI to implement the following
```
     def index_audio(self, name=None, continuous=True,
                     model="en-US_BroadbandModel", word_confidence=True,
-                    word_alternatives_threshold=0.9, keywords=None,
+                    word_alternatives_threshold=0.9, keywords=None, inactivity_timeout=30,
                     keywords_threshold=None,
                     profanity_filter_for_US_results=False):
```
and
```
        if inactivity_timeout is not None:
            params['inactivity_timeout'] = inactivity_timeout
```
And it worked through the whole file then.
The regularizer may help.  I'm somewhat surprised how weak the Watson speech recognizer is, even when I provide a-priori keywords.  It works, but I'd say that its only 60-70% accurate.  I guess we will need to *enunciate* in the future.  :-)
Thanks for writing such an awesome package!

**Comment by aalireza** [comment]
I see, so `inactivity_timeout` was the problem. I'll fix it!

Yeah. It's not perfect at all, but among the available options, it's the most accurate and the only thing we can do is to basically make audio more suitable e.g. fiddle the encoding or create a noise profile from random samples and filter them out etc. My personal problem was actually with having to upload one's files instead of processing them locally. For that I'm working on a wavenet based approach, but I'm a a beginner and am not sure it'd work as well as it should.

Anyway glad everything is working.
